INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10001, 'zeeshan', 'Get AWS certified', CURRENT_DATE(), false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10002, 'zeeshan', 'Learn to Sing', CURRENT_DATE(), false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10003, 'zeeshan', 'Get Azure certification', CURRENT_DATE(), false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10004, 'zeeshan', 'Get GCP certification', CURRENT_DATE(), false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10005, 'zeeshan', 'Get Spring Boot Certificate', CURRENT_DATE(), false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10006, 'in28mins', 'Get AWS certified', CURRENT_DATE(), false);